import pygame
pygame.mixer.init()

player_jump = pygame.mixer.Sound('maro-jump-sound-effect_1.mp3')
player_jump.set_volume(0.1)
player_jump_h = pygame.mixer.Sound('sm64_mario_boing-online-audio-converter.mp3')
player_jump_h.set_volume(0.25)
heal = pygame.mixer.Sound('01-power-up-mario.mp3')
heal.set_volume(0.3)
pow = pygame.mixer.Sound('super-mario-64-thwomp-sound-online-audio-converter.mp3')
pow.set_volume(0.3)
oof = pygame.mixer.Sound('sm64_mario_oof.mp3')
oof.set_volume(0.3)
boom = pygame.mixer.Sound('mario-goomba-stomp.mp3')
boom.set_volume(0.85)
battle1 = pygame.mixer.Sound("2-08. Dino Piranha.mp3")
battle1.set_volume(0.25)
win_battle1 = pygame.mixer.Sound("1-10. You Got a Moon! 1.mp3")
win_battle1.set_volume(0.25)
to_the_next = pygame.mixer.Sound("18 To the Next World.mp3")
to_the_next.set_volume(0.65)
ded = pygame.mixer.Sound("lose1.mp3")
ded.set_volume(1)
battle2 = pygame.mixer.Sound("106. Bouldergeist.mp3")
battle2.set_volume(0.45)
win_e = pygame.mixer.Sound("11. Super Mario Bros. Remix.mp3")
win_e.set_volume(1)