import pygame

super_heart = pygame.image.load('super_heart.png')
super_heart = pygame.transform.scale(super_heart, (300, 300))
boom_oouch = pygame.image.load('boom-boom_hit1.png')
boom_block = pygame.image.load('boom-boom_block.png')
boom_block_jump = pygame.image.load('boom-boom_block_jump.png')
boom_block_fall = pygame.image.load('boom-boom_block_fall.png')
boom_idle = pygame.image.load('boom-boom_idle.png')
boom_jump = pygame.image.load('boom-boom_jump.png')
boom_oouch = pygame.transform.scale(boom_oouch, (800, 800))
boom_block = pygame.transform.scale(boom_block, (900, 900))
boom_block_jump = pygame.transform.scale(boom_block_jump, (900, 900))
boom_block_fall = pygame.transform.scale(boom_block_fall, (900, 900))
boom_idle = pygame.transform.scale(boom_idle, (800, 800))
boom_jump = pygame.transform.scale(boom_jump, (800, 800))


boomwlk = [pygame.image.load('boom-boom1.png'), pygame.image.load('boom-boom2.png')]
boomwlk[0] = pygame.transform.scale(boomwlk[0], (800, 800))
boomwlk[1] = pygame.transform.scale(boomwlk[1], (800, 800))
boomdead = [pygame.image.load('boom-boom_dead1.png'), pygame.image.load('boom-boom_dead2.png')]
boomdead[0] = pygame.transform.scale(boomdead[0], (800, 800))
boomdead[1] = pygame.transform.scale(boomdead[1], (800, 800))
mario_crouch = pygame.image.load('mario_crouch.png')
mario_ouuch = pygame.image.load('mario_dead.png')
mario_l = pygame.image.load('mario_left.png')
mario_r = pygame.image.load('mario_right.png')
mario_l_fall = pygame.image.load('mario_fall_left.png')
mario_r_fall = pygame.image.load('mario_fall_right.png')
mario_r_jump = pygame.image.load('mario_right_jump.png')
mario_cro_jump = pygame.image.load('mario_crouch_jump.png')
mario_l_jump = pygame.image.load('mario_left_jump.png')
mario_r_wlk = [pygame.image.load('mario_right_0.png'), pygame.image.load('mario_right_1.png'), pygame.image.load('mario_right_2.png')]
mario_l_wlk = [pygame.image.load('mario_left_0.png'), pygame.image.load('mario_left_1.png'), pygame.image.load('mario_left_2.png')]
mario_r_wlk[0] = pygame.transform.scale(mario_r_wlk[0], (300, 300))
mario_r_wlk[1] = pygame.transform.scale(mario_r_wlk[1], (300, 300))
mario_r_wlk[2] = pygame.transform.scale(mario_r_wlk[2], (300, 300))
mario_l_wlk[0] = pygame.transform.scale(mario_l_wlk[0], (300, 300))
mario_l_wlk[1] = pygame.transform.scale(mario_l_wlk[1], (300, 300))
mario_l_wlk[2] = pygame.transform.scale(mario_l_wlk[2], (300, 300))
mario_crouch = pygame.transform.scale(mario_crouch, (300, 300))
mario_ouuch = pygame.transform.scale(mario_ouuch, (300, 300))
mario_r_jump = pygame.transform.scale(mario_r_jump, (300, 300))
mario_l_jump = pygame.transform.scale(mario_l_jump, (300, 300))
mario_cro_jump = pygame.transform.scale(mario_cro_jump, (300, 300))
mario_r_fall = pygame.transform.scale(mario_r_fall, (300, 300))
mario_l_fall = pygame.transform.scale(mario_l_fall, (300, 300))

bould_idle = [pygame.image.load('bouldergeist_idle1.png'), pygame.image.load('bouldergeist_idle2.png')]
bould_idle[0] = pygame.transform.scale(bould_idle[0], (1600, 1600))
bould_idle[1] = pygame.transform.scale(bould_idle[1], (1600, 1600))
bould_dead = [pygame.image.load('bouldergeist_dead1.png'), pygame.image.load('bouldergeist_dead2.png')]
bould_dead[0] = pygame.transform.scale(bould_dead[0], (1600, 1600))
bould_dead[1] = pygame.transform.scale(bould_dead[1], (1600, 1600))
bould_ouch= pygame.image.load('bouldergeist_ouch.png')
bould_ouch = pygame.transform.scale(bould_ouch, (1600,1600))
rock_whole = pygame.image.load('rock1.png')
rock_whole = pygame.transform.scale(rock_whole, (1000,1000))
rock_cracked = pygame.image.load('rock2.png')
rock_cracked = pygame.transform.scale(rock_cracked, (1000,1000))
rock_broken = pygame.image.load('rock_broken.png')
rock_broken = pygame.transform.scale(rock_broken, (1000,1000))
spike_idle = [pygame.image.load('bouldergeist_hand_idle1.png'), pygame.image.load('bouldergeist_hand_idle2.png')]
spike_idle[0] = pygame.transform.scale(spike_idle[0], (1000, 1000))
spike_idle[1] = pygame.transform.scale(spike_idle[1], (1000, 1000))
spike_attack = [pygame.image.load('bouldergeist_hand_attack1.png'), pygame.image.load('bouldergeist_hand_attack2.png')]
spike_attack[0] = pygame.transform.scale(spike_attack[0], (1000, 1000))
spike_attack[1] = pygame.transform.scale(spike_attack[1], (1000, 1000))